### ISSUE TITLE
caching mode is not working，I want this feature

### ISSUE THREAD

**Issue by TheSecondAkari** [mikekwright/vscode-terminal-capture#2]
it shows error:  rejected promise not handled within 1 second: TypeError: terminal.onDidWriteData is not a function

Is there any other way to achieve?

**Comment by TheSecondAkari** [comment]
I know how to resolve。thanks

**Comment by YannLynn** [comment]
> I know how to resolve。thanks

可以分享一下怎么解决的吗～

**Comment by TheSecondAkari** [comment]
不好意思，时间比较久远了。 不记得怎么处理了。 我项目的东西也没保存，删掉了。
当时设想的是做一个vscode插件：”捕获终端的错误信息，然后自动去搜索引擎进行搜索，然后给出如何处理的说明“。 当时发现无法完全识别终端的错误信息、搜索引擎的结果也各种杂乱信息，然后就没做了。【或许现在结合gpt有点点用】

**Comment by YannLynn** [comment]
感谢回答～ 我的需求目前也是另一种方式实现了。

分享一下当时我在互联网上搜索的结果吧。首先 terminal.onDidWriteData 是一个实验性的 api，后来应该是下架了 2333。
如果按照要获取终端信息的思路做的话，我当时找了一个备选的方案，可以参考这两个链接：

https://github.com/microsoft/vscode/issues/83927 

https://github.com/microsoft/vscode/issues/82329 / 

但是具体实现方面我没有深入尝试，因为换方案了，只能说作为一个尝试的方向 👆

**Comment by TheSecondAkari** [comment]
> 感谢回答～ 我的需求目前也是另一种方式实现了。
> 
> 分享一下当时我在互联网上搜索的结果吧。首先 terminal.onDidWriteData 是一个实验性的 api，后来应该是下架了 2333。 如果按照要获取终端信息的思路做的话，我当时找了一个备选的方案，可以参考这两个链接：
> 
> [microsoft/vscode#83927](https://github.com/microsoft/vscode/issues/83927)
> 
> [microsoft/vscode#82329](https://github.com/microsoft/vscode/issues/82329) /
> 
> 但是具体实现方面我没有深入尝试，因为换方案了，只能说作为一个尝试的方向 👆

谢谢！！
